#!/bin/sh
# dont think this script needs to exist, kinda lost the meaning of it while programming but scared to delete it cuz what if it fucks everyhting up.

usage () {
	echo "$0 <lib name> <evil function name> <bytecount>"
}

if [ "$#" -ne 3 ]; then
	usage
	exit 1
fi

LIB="$1"
FUNC="$2"
BYTECOUNT="$3"

if [ ! -f "$LIB" ]; then
	echo "Error: Library file '$LIB' not found" >&2
	exit 1
fi

OBJDUMP_OUT=$(objdump -d "$LIB" 2>&1)
if [ $? -ne 0 ]; then
	echo "Error: objdump failed on '$LIB'" >&2
	exit 1
fi

if ! echo "$OBJDUMP_OUT" | grep -q "<${FUNC}>:"; then
	echo "Error: Function '${FUNC}' not found in '$LIB'" >&2
	exit 1
fi

# sorry for anyone reading this
# basically grabs the function from objdump, strips all the addresses and instruction text, just keeps the raw hex bytes and converts em to \x format for C strings
extract_hex_bytes() {
	echo "$OBJDUMP_OUT" | \
		sed -n "/<${FUNC}>:/,/^$/p" | \
		grep -v "<${FUNC}>:" | \
		head -n 30 | \
		sed 's/^[[:space:]]*[0-9a-fA-F]*:[[:space:]]*//' | \
		sed 's/[[:space:]][[:space:]].*$//' | \
		tr '\n' ' ' | \
		sed -E 's/([0-9a-fA-F]{2})/\\x\1/g' | \
		sed -E 's/[[:space:]]//g'
}

# why tf did i do this
# same shit as above but only looks for the specific "c7 45 f4" instruction pattern (that mov thing) and extracts just that one line
extract_tc_bytes() {
	echo "$OBJDUMP_OUT" | \
		sed -n "/<${FUNC}>:/,/^$/p" | \
		grep "c7 45 f4" | \
		head -n 1 | \
		sed 's/^[[:space:]]*[0-9a-fA-F]*:[[:space:]]*//' | \
		sed 's/[[:space:]][[:space:]].*$//' | \
		tr '\n' ' ' | \
		sed -E 's/([0-9a-fA-F]{2})/\\x\1/g' | \
		sed -E 's/[[:space:]]//g'
}

EVILSIG=$(extract_hex_bytes | cut -c1-$((4*$BYTECOUNT)))
TC=$(extract_tc_bytes | cut -c1-16)

echo "// DO NOT MODIFY: AUTOGENERATED"
echo "static char const evilsig[] = \"${EVILSIG}\";"
echo "static char const tc[] = \"${TC}\";"
